### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 0522ash** [0522ash/furima-34453#9]
#URL
https://furima-34453.herokuapp.com/

Basic認証のID
ito
パスワード
asuka

出品者用のメールアドレス
test@test
パスワード
test00

購入者用のメールアドレス
testtest@test
パスワード
test01

**Comment by runak25033** [comment]
ご提出ありがとうございます‼︎

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
<img width="916" alt="最終課題LGTM2" src="https://user-images.githubusercontent.com/79125420/111097838-9f054780-8585-11eb-9ab4-6115606ef980.png">
